//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Testovyjj_proekt
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car.
    /// </summary>
    // *** Start programmer edit section *** (Car CustomAttributes)

    // *** End programmer edit section *** (Car CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CarE", new string[] {
            "Name as \'Name\'",
            "MaxSpeed as \'Max speed\'",
            "Driver as \'Driver\'",
            "Driver.Name as \'Name\'"}, Hidden=new string[] {
            "Driver.Name"})]
    [MasterViewDefineAttribute("CarE", "Driver", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CarL", new string[] {
            "Name as \'Name\'",
            "MaxSpeed as \'Max speed\'",
            "Driver.Name as \'Name\'"})]
    public class Car : ICSSoft.STORMNET.DataObject
    {

        private float fMaxSpeed;

        private string fName;

        private IIS.Testovyjj_proekt.Driver fDriver;

        // *** Start programmer edit section *** (Car CustomMembers)

        // *** End programmer edit section *** (Car CustomMembers)


        /// <summary>
        /// MaxSpeed.
        /// </summary>
        // *** Start programmer edit section *** (Car.MaxSpeed CustomAttributes)

        // *** End programmer edit section *** (Car.MaxSpeed CustomAttributes)
        public virtual float MaxSpeed
        {
            get
            {
                // *** Start programmer edit section *** (Car.MaxSpeed Get start)

                // *** End programmer edit section *** (Car.MaxSpeed Get start)
                float result = this.fMaxSpeed;
                // *** Start programmer edit section *** (Car.MaxSpeed Get end)

                // *** End programmer edit section *** (Car.MaxSpeed Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.MaxSpeed Set start)

                // *** End programmer edit section *** (Car.MaxSpeed Set start)
                this.fMaxSpeed = value;
                // *** Start programmer edit section *** (Car.MaxSpeed Set end)

                // *** End programmer edit section *** (Car.MaxSpeed Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Car.Name CustomAttributes)

        // *** End programmer edit section *** (Car.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Car.Name Get start)

                // *** End programmer edit section *** (Car.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Car.Name Get end)

                // *** End programmer edit section *** (Car.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.Name Set start)

                // *** End programmer edit section *** (Car.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Car.Name Set end)

                // *** End programmer edit section *** (Car.Name Set end)
            }
        }

        /// <summary>
        /// Car.
        /// </summary>
        // *** Start programmer edit section *** (Car.Driver CustomAttributes)

        // *** End programmer edit section *** (Car.Driver CustomAttributes)
        [PropertyStorage(new string[] {
                "Driver"})]
        [NotNull()]
        public virtual IIS.Testovyjj_proekt.Driver Driver
        {
            get
            {
                // *** Start programmer edit section *** (Car.Driver Get start)

                // *** End programmer edit section *** (Car.Driver Get start)
                IIS.Testovyjj_proekt.Driver result = this.fDriver;
                // *** Start programmer edit section *** (Car.Driver Get end)

                // *** End programmer edit section *** (Car.Driver Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.Driver Set start)

                // *** End programmer edit section *** (Car.Driver Set start)
                this.fDriver = value;
                // *** Start programmer edit section *** (Car.Driver Set end)

                // *** End programmer edit section *** (Car.Driver Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "CarE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarE", typeof(IIS.Testovyjj_proekt.Car));
                }
            }

            /// <summary>
            /// "CarL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarL", typeof(IIS.Testovyjj_proekt.Car));
                }
            }
        }
    }
}

