//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Testovyjj_proekt
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Driver.
    /// </summary>
    // *** Start programmer edit section *** (Driver CustomAttributes)

    // *** End programmer edit section *** (Driver CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DriverE", new string[] {
            "Name as \'Name\'",
            "Age as \'Age\'"})]
    [View("DriverL", new string[] {
            "Name as \'Name\'",
            "Age as \'Age\'"})]
    public class Driver : ICSSoft.STORMNET.DataObject
    {

        private int fAge;

        private string fName;

        // *** Start programmer edit section *** (Driver CustomMembers)

        // *** End programmer edit section *** (Driver CustomMembers)


        /// <summary>
        /// Age.
        /// </summary>
        // *** Start programmer edit section *** (Driver.Age CustomAttributes)

        // *** End programmer edit section *** (Driver.Age CustomAttributes)
        public virtual int Age
        {
            get
            {
                // *** Start programmer edit section *** (Driver.Age Get start)

                // *** End programmer edit section *** (Driver.Age Get start)
                int result = this.fAge;
                // *** Start programmer edit section *** (Driver.Age Get end)

                // *** End programmer edit section *** (Driver.Age Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Driver.Age Set start)

                // *** End programmer edit section *** (Driver.Age Set start)
                this.fAge = value;
                // *** Start programmer edit section *** (Driver.Age Set end)

                // *** End programmer edit section *** (Driver.Age Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Driver.Name CustomAttributes)

        // *** End programmer edit section *** (Driver.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Driver.Name Get start)

                // *** End programmer edit section *** (Driver.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Driver.Name Get end)

                // *** End programmer edit section *** (Driver.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Driver.Name Set start)

                // *** End programmer edit section *** (Driver.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Driver.Name Set end)

                // *** End programmer edit section *** (Driver.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "DriverE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DriverE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DriverE", typeof(IIS.Testovyjj_proekt.Driver));
                }
            }

            /// <summary>
            /// "DriverL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DriverL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DriverL", typeof(IIS.Testovyjj_proekt.Driver));
                }
            }
        }
    }
}

